source 'http://rubygems.org'

ruby '2.4.3'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'puma'
gem 'turnout'
gem 'rake'
gem 'capistrano'
gem 'capistrano-bundler'
gem 'capistrano-rbenv'
gem 'capistrano3-puma', github: 'seuros/capistrano-puma'
gem 'google-cloud-datastore'
gem 'rollbar'
